/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class great_doctor_sincerity_SignJni */

#ifndef _Included_great_doctor_sincerity_SignJni
#define _Included_great_doctor_sincerity_SignJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     great_doctor_sincerity_SignJni
 * Method:    getSign
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_great_doctor_sincerity_SignJni_getSign
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
